databases:
  - name: saitama2nd_DB
    databaseName: saitama2nd_db
    user: saitama2nd
    region: singapore

services:
  - type: web
    name: saitama2nd
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saitama2nd_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

